version: '3'
services:
    crawler:
        image: derhenning/mopsy-crawler-calibre:latest
        ports:
            - 80:5000
        environment:
            CRAWLER_NAME: Calibre
            MOPSY_MYSQL_DATABASE: mopsy
            MOPSY_MYSQL_HOST: db
            MOPSY_MYSQL_PORT: 3306
            MOPSY_MYSQL_USERNAME: mopsy
            MOPSY_MYSQL_PASSWORD: mopsy
            MOPSY_SOLR_HOST: solr
            MOPSY_SOLR_PORT: 8983
            MOPSY_SOLR_CORE: dvcore