version: '3'
services:
    crawler:
        image: derhenning/mopsy-crawler:latest
        ports:
            - 5000:80
        volumes:
            - /volume1/media/books:/mnt/books:ro
        environment:
            PORT: 80
            DEBUG: false
            CRAWLER_TYPE: calibre
            CRAWLER_NAME: Calibre V1.0
            CALIBRE_PATH: /mnt/books
            MOPSY_SOLR_HOST: solr
            MOPSY_SOLR_PORT: 8983
            MOPSY_SOLR_CORE: mopsy
            MOPSY_SOLR_PREFIX: calibre