version: '3'
services:
    crawler:
        build: .
        ports:
            - 5000:5000
        volumes:
            - /volume1/media/books:/books:ro
        environment:
            CRAWLER_NAME: Calibre
            MOPSY_MYSQL_DATABASE: mopsy
            MOPSY_MYSQL_HOST: db
            MOPSY_MYSQL_PORT: 3306
            MOPSY_MYSQL_USERNAME: mopsy
            MOPSY_MYSQL_PASSWORD: mopsy
            MOPSY_SOLR_HOST: solr
            MOPSY_SOLR_PORT: 8983
            MOPSY_SOLR_CORE: dvcore
            MOPSY_SOLR_PREFIX: calibre